# 
[[redirects]]
  from = "/lucky"
  to = "https://mint.x402hood.xyz/.netlify/functions/lucky"
  status = 200

# 
[[redirects]]
  from = "/mint"
  to = "https://mint.x402hood.xyz/.netlify/functions/mint"
  status = 200

  # 
[[redirects]]
  from = "/mint"
  to = "https://mint.x402hood.xyz/.netlify/functions/resource"
  status = 200

  # 
[[redirects]]
  from = "/mint"
  to = "https://mint.x402hood.xyz/.netlify/functions/agent"
  status = 200

    # 
[[redirects]]
  from = "/mint"
  to = "https://mint.x402hood.xyz/.netlify/functions/mint5"
  status = 200

  # 
[[redirects]]
  from = "/mint"
  to = "https://mint.x402hood.xyz/.netlify/functions/mint_hood"
  status = 200